return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "vim",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "yaml",
      "dockerfile",
      "hcl",
      "go",
      "terraform",
      "csv",
      "go",
      "nginx",
      "sql",
    },
    sync_install = true,
    highlight = { enable = true },
    indent = { enable = true },
    ignore_install = { enable = false },
  },
}
